import React from 'react';
import { ApiSource } from './types';
import { DeputiesIcon, LegislaturesIcon, PartiesIcon, VotesIcon, BillsIcon, OrgansIcon, EventsIcon, ReferencesIcon, FrentesIcon, GruposIcon, BlocosIcon, SenadoIcon, CamaraIcon, DiscursoIcon, ParlamentarIcon, PlenarioIcon, ProcessoIcon, LegislacaoIcon, OrcamentoIcon } from './components/icons';

export const API_SOURCES: ApiSource[] = [
  {
    name: 'Câmara dos Deputados',
    baseUrl: 'https://dadosabertos.camara.leg.br/api/v2',
    icon: CamaraIcon,
    categories: [
        {
        name: 'Deputados',
        icon: DeputiesIcon,
        endpoints: [
          {
            id: 'getDeputados',
            method: 'GET',
            path: '/deputados',
            description: 'Retorna uma lista de dados básicos sobre deputados que estiveram em exercício parlamentar.',
            longDescription: 'Retorna uma lista de dados básicos sobre deputados que estiveram em exercício parlamentar. Você pode filtrar por vários parâmetros para refinar os resultados.',
            parameters: [
              { name: 'id', type: 'query', description: 'ID do deputado (separados por vírgula).', autocomplete: 'deputados'},
              { name: 'nome', type: 'query', description: 'Parte do nome parlamentar.' },
              { name: 'siglaUf', type: 'query', description: 'Sigla da UF (e.g., SP, RJ).', options: ['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO'] },
              { name: 'siglaPartido', type: 'query', description: 'Sigla do partido (e.g., PT, PL).', autocomplete: 'partidos_sigla' },
              { name: 'pagina', type: 'query', description: 'Número da página de resultados.' },
              { name: 'itens', type: 'query', description: 'Número de itens por página.' },
            ],
          },
          {
            id: 'getDeputadoById',
            method: 'GET',
            path: '/deputados/{id}',
            description: 'Retorna os dados cadastrais de um parlamentar específico.',
            longDescription: 'Retorna os dados cadastrais de um parlamentar específico, identificado pelo seu ID.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico do parlamentar.', required: true, autocomplete: 'deputados' },
            ],
          },
          {
            id: 'getDeputadoDespesas',
            method: 'GET',
            path: '/deputados/{id}/despesas',
            description: 'Retorna as despesas com exercício parlamentar do deputado.',
            longDescription: 'Acessa os registros de pagamentos e reembolsos feitos pela Câmara em prol do deputado, a título da Cota para Exercício da Atividade Parlamentar. Se não forem passados parâmetros de tempo, o serviço retorna dados dos seis meses anteriores à requisição.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico do parlamentar.', required: true, autocomplete: 'deputados' },
              { name: 'idLegislatura', type: 'query', description: 'ID da legislatura.', autocomplete: 'legislaturas'},
              { name: 'ano', type: 'query', description: 'Ano da despesa (e.g., 2023).' },
              { name: 'mes', type: 'query', description: 'Mês da despesa (e.g., 1-12).' },
              { name: 'cnpjCpfFornecedor', type: 'query', description: 'CNPJ ou CPF do fornecedor.'},
              { name: 'pagina', type: 'query', description: 'Número da página.' },
              { name: 'itens', type: 'query', description: 'Itens por página.' },
              { name: 'ordenarPor', type: 'query', description: 'Campo para ordenação.'},
            ],
          },
          {
            id: 'getDeputadoDiscursos',
            method: 'GET',
            path: '/deputados/{id}/discursos',
            description: 'Lista de discursos feitos por um deputado.',
            longDescription: 'Retorna uma lista de informações sobre os discursos feitos pelo deputado identificado. Se não forem configurados parâmetros de tempo, são buscados os discursos dos sete dias anteriores à requisição.',
            parameters: [
                { name: 'id', type: 'path', description: 'ID do deputado.', required: true, autocomplete: 'deputados' },
                { name: 'dataInicio', type: 'query', description: 'Data de início (AAAA-MM-DD).'},
                { name: 'dataFim', type: 'query', description: 'Data de fim (AAAA-MM-DD).'},
            ],
          },
          {
            id: 'getDeputadoEventos',
            method: 'GET',
            path: '/deputados/{id}/eventos',
            description: 'Lista de eventos com a participação de um deputado.',
            longDescription: 'Retorna uma lista de eventos nos quais a participação do parlamentar identificado era ou é prevista. Se não forem passados parâmetros de tempo, são retornados os eventos num período de cinco dias, sendo dois antes e dois depois do dia da requisição.',
            parameters: [
                { name: 'id', type: 'path', description: 'ID do deputado.', required: true, autocomplete: 'deputados' },
            ],
          },
          {
            id: 'getDeputadoFrentes',
            method: 'GET',
            path: '/deputados/{id}/frentes',
            description: 'Frentes parlamentares das quais um deputado é integrante.',
            longDescription: 'Retorna uma lista de informações básicas sobre as frentes parlamentares das quais o parlamentar identificado é membro.',
            parameters: [
                { name: 'id', type: 'path', description: 'ID do deputado.', required: true, autocomplete: 'deputados' },
            ],
          },
          {
            id: 'getDeputadoOcupacoes',
            method: 'GET',
            path: '/deputados/{id}/ocupacoes',
            description: 'Empregos e atividades que o deputado já teve.',
            longDescription: 'Enumera as atividades profissionais ou ocupacionais que o deputado identificado já teve em sua carreira e declarou à Câmara dos Deputados.',
            parameters: [
                { name: 'id', type: 'path', description: 'ID do deputado.', required: true, autocomplete: 'deputados' },
            ],
          },
          {
            id: 'getDeputadoOrgaos',
            method: 'GET',
            path: '/deputados/{id}/orgaos',
            description: 'Órgãos dos quais um deputado é integrante.',
            longDescription: 'Retorna uma lista de órgãos, como as comissões e procuradorias, dos quais o deputado identificado participa ou participou. Se não for passado parâmetro de tempo, são retornados os órgãos ocupados pelo parlamentar no momento da requisição.',
            parameters: [
                { name: 'id', type: 'path', description: 'ID do deputado.', required: true, autocomplete: 'deputados' },
            ],
          },
          {
            id: 'getDeputadoHistorico',
            method: 'GET',
            path: '/deputados/{id}/historico',
            description: 'Lista de mudanças no exercício parlamentar de um deputado (mudança de partido, licenças, etc.).',
            longDescription: 'Este serviço retorna uma listagem com as diferentes situações de exercício parlamentar do deputado identificado por {id}, mesmo que a alteração registrada não tenha afetado o andamento do mandato.',
            parameters: [
                { name: 'id', type: 'path', description: 'ID do deputado.', required: true, autocomplete: 'deputados' },
                { name: 'dataInicio', type: 'query', description: 'Data de início (AAAA-MM-DD).'},
                { name: 'dataFim', type: 'query', description: 'Data de fim (AAAA-MM-DD).'},
            ],
          },
          {
            id: 'getDeputadoMandatosExternos',
            method: 'GET',
            path: '/deputados/{id}/mandatosExternos',
            description: 'Lista outros cargos eletivos que o parlamentar já exerceu fora da Câmara dos Deputados.',
            longDescription: 'Retorna uma lista em que cada item traz informações básicas sobre um cargo para o qual o parlamentar identificado por {id} tenha sido eleito, em sua carreira política fora da Câmara dos Deputados.',
            parameters: [
                { name: 'id', type: 'path', description: 'ID do deputado.', required: true, autocomplete: 'deputados' },
            ],
          },
          {
            id: 'getDeputadoProfissoes',
            method: 'GET',
            path: '/deputados/{id}/profissoes',
            description: 'Apresenta as profissões que o parlamentar declarou à Câmara.',
            longDescription: 'Retorna uma lista de dados sobre profissões que o parlamentar identificado por {id} declarou à Câmara que já exerceu ou que pode exercer pela sua formação e/ou experiência.',
            parameters: [
                { name: 'id', type: 'path', description: 'ID do deputado.', required: true, autocomplete: 'deputados' },
            ],
          },
        ],
      },
        {
        name: 'Frentes',
        icon: FrentesIcon,
        endpoints: [
          {
            id: 'getFrentes',
            method: 'GET',
            path: '/frentes',
            description: 'Retorna uma lista de frentes parlamentares.',
            longDescription: 'Retorna uma lista de informações sobre uma frente parlamentar. Se omitido, são retornadas todas as frentes parlamentares criadas desde 2003.',
            parameters: [
               { name: 'idLegislatura', type: 'query', description: 'ID da legislatura.', autocomplete: 'legislaturas' },
            ],
          },
          {
            id: 'getFrenteById',
            method: 'GET',
            path: '/frentes/{id}',
            description: 'Retorna informações detalhadas sobre uma frente parlamentar.',
            longDescription: 'Este recurso traz informações detalhadas sobre a frente parlamentar identificada por {id}.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico da frente.', required: true, autocomplete: 'frentes' },
            ],
          },
           {
            id: 'getFrenteMembros',
            method: 'GET',
            path: '/frentes/{id}/membros',
            description: 'Retorna uma lista de deputados membros de uma frente.',
            longDescription: 'Uma lista dos deputados participantes da frente parlamentar identificada por {id} e os papéis que exerceram nessa frente (signatário, coordenador ou presidente).',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico da frente.', required: true, autocomplete: 'frentes' },
            ],
          },
        ],
      },
      {
        name: 'Partidos',
        icon: PartiesIcon,
        endpoints: [
          {
            id: 'getPartidos',
            method: 'GET',
            path: '/partidos',
            description: 'Retorna uma lista de partidos políticos que têm ou já tiveram deputados.',
            longDescription: 'Retorna uma lista de dados básicos sobre os partidos políticos que têm ou já tiveram deputados na Câmara. Se não forem passados parâmetros, o serviço retorna os partidos que têm deputados em exercício no momento da requisição.',
            parameters: [
               { name: 'sigla', type: 'query', description: 'Sigla do partido (e.g., PT, PL).', autocomplete: 'partidos_sigla' },
               { name: 'dataInicio', type: 'query', description: 'Data de início (AAAA-MM-DD).'},
               { name: 'dataFim', type: 'query', description: 'Data de fim (AAAA-MM-DD).'},
            ],
          },
          {
            id: 'getPartidoById',
            method: 'GET',
            path: '/partidos/{id}',
            description: 'Retorna informações detalhadas sobre um partido.',
            longDescription: 'Retorna informações detalhadas sobre um partido, incluindo dados sobre sua situação e seu líder atual.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico do partido.', required: true, autocomplete: 'partidos' },
            ],
          },
           {
            id: 'getPartidoMembros',
            method: 'GET',
            path: '/partidos/{id}/membros',
            description: 'Retorna uma lista de deputados membros de um partido.',
            longDescription: 'Retorna uma lista de deputados que estão ou estiveram em exercício pelo partido {id}.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico do partido.', required: true, autocomplete: 'partidos' },
            ],
          },
          {
            id: 'getPartidoLideres',
            method: 'GET',
            path: '/partidos/{id}/lideres',
            description: 'Lista de líderes e vice-líderes de um partido.',
            longDescription: 'Retorna uma lista de deputados que ocupam ou ocuparam cargos de líder ou vice-líder do partido {id} num intervalo de tempo opcional, com a identificação do cargo e o período em que o tiveram.',
            parameters: [
                { name: 'id', type: 'path', description: 'ID do partido.', required: true, autocomplete: 'partidos' },
            ],
          },
        ],
      },
       {
        name: 'Votações',
        icon: VotesIcon,
        endpoints: [
          {
            id: 'getVotacoes',
            method: 'GET',
            path: '/votacoes',
            description: 'Retorna uma lista de informações básicas sobre as votações ocorridas.',
            longDescription: 'Retorna uma lista de informações básicas sobre as votações ocorridas em eventos dos diversos órgãos da Câmara. Se não forem passados parâmetros que definam o intervalo de tempo da pesquisa, são retornados dados sobre todas as votações ocorridas nos últimos 30 dias.',
            parameters: [
                { name: 'dataInicio', type: 'query', description: 'Data de início (AAAA-MM-DD).' },
                { name: 'dataFim', type: 'query', description: 'Data de fim (AAAA-MM-DD).' },
                { name: 'idProposicao', type: 'query', description: 'ID da proposição.', autocomplete: 'proposicoes'}
            ],
          },
          {
            id: 'getVotacaoById',
            method: 'GET',
            path: '/votacoes/{id}',
            description: 'Retorna informações detalhadas sobre uma votação específica.',
            longDescription: 'Retorna um conjunto detalhado de dados sobre a votação identificada por {id}, tais como as proposições que podem ter sido o objeto da votação e os efeitos de tramitação de outras proposições que eventualmente tenham sido cadastradas em consequência desta votação.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID alfanumérico da votação.', required: true, autocomplete: 'votacoes' },
            ],
          },
           {
            id: 'getVotacaoVotos',
            method: 'GET',
            path: '/votacoes/{id}/votos',
            description: 'Retorna como cada parlamentar votou em uma votação.',
            longDescription: 'Se {id} é o identificador de uma votação nominal da Câmara que não tenha sido secreta, este endpoint retorna uma lista em que cada item contém os identificadores básicos de um deputado e o voto ou posicionamento que ele registrou.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID alfanumérico da votação.', required: true, autocomplete: 'votacoes' },
            ],
          },
           {
            id: 'getVotacaoOrientacoes',
            method: 'GET',
            path: '/votacoes/{id}/orientacoes',
            description: 'O voto recomendado pelas lideranças.',
            longDescription: 'Se a votação identificada por {id} teve orientações, este recurso retorna uma lista em que cada item contém os identificadores de um partido, bloco ou liderança, e o posicionamento ou voto que foi recomendado aos seus parlamentares.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID alfanumérico da votação.', required: true, autocomplete: 'votacoes' },
            ],
          },
        ],
      },
      {
        name: 'Proposições',
        icon: BillsIcon,
        endpoints: [
            {
                id: 'getProposicoes',
                method: 'GET',
                path: '/proposicoes',
                description: 'Lista de informações básicas sobre projetos de lei, resoluções, etc.',
                longDescription: 'Lista informações básicas sobre projetos de lei, resoluções, medidas provisórias, emendas, pareceres e todos os outros tipos de proposições na Câmara. Por padrão, são retornadas todas as proposições apresentadas ou que tiveram mudança de situação nos últimos 30 dias.',
                parameters: [
                    { name: 'ano', type: 'query', description: 'Ano de apresentação.' },
                    { name: 'siglaTipo', type: 'query', description: 'Sigla do tipo (e.g., PL, PEC).', autocomplete: 'proposicoes_siglaTipo' },
                    { name: 'numero', type: 'query', description: 'Número da proposição.' },
                    { name: 'idDeputadoAutor', type: 'query', description: 'ID do deputado autor.', autocomplete: 'deputados' },
                ],
            },
            {
                id: 'getProposicaoById',
                method: 'GET',
                path: '/proposicoes/{id}',
                description: 'Informações detalhadas sobre uma proposição específica.',
                parameters: [
                    { name: 'id', type: 'path', description: 'ID numérico da proposição.', required: true, autocomplete: 'proposicoes' },
                ],
            },
            {
                id: 'getProposicaoAutores',
                method: 'GET',
                path: '/proposicoes/{id}/autores',
                description: 'Lista pessoas e/ou entidades autoras de uma proposição.',
                parameters: [
                    { name: 'id', type: 'path', description: 'ID numérico da proposição.', required: true, autocomplete: 'proposicoes' },
                ],
            },
            {
                id: 'getProposicaoRelacionadas',
                method: 'GET',
                path: '/proposicoes/{id}/relacionadas',
                description: 'Lista de proposições relacionadas a uma em especial.',
                parameters: [
                    { name: 'id', type: 'path', description: 'ID da proposição.', required: true, autocomplete: 'proposicoes' },
                ],
            },
            {
                id: 'getProposicaoTramitacoes',
                method: 'GET',
                path: '/proposicoes/{id}/tramitacoes',
                description: 'O histórico de passos na tramitação de uma proposta.',
                parameters: [
                    { name: 'id', type: 'path', description: 'ID da proposição.', required: true, autocomplete: 'proposicoes' },
                ],
            },
            {
                id: 'getProposicaoVotacoes',
                method: 'GET',
                path: '/proposicoes/{id}/votacoes',
                description: 'Votações sobre uma proposição específica.',
                parameters: [
                    { name: 'id', type: 'path', description: 'ID da proposição.', required: true, autocomplete: 'proposicoes' },
                ],
            },
            {
                id: 'getProposicaoTemas',
                method: 'GET',
                path: '/proposicoes/{id}/temas',
                description: 'Apresenta a lista de áreas temáticas com as quais uma proposição se relaciona.',
                parameters: [
                    { name: 'id', type: 'path', description: 'ID da proposição.', required: true, autocomplete: 'proposicoes' },
                ],
            },
        ],
      },
      {
        name: 'Legislaturas',
        icon: LegislaturesIcon,
        endpoints: [
          {
            id: 'getLegislaturas',
            method: 'GET',
            path: '/legislaturas',
            description: 'Lista os períodos de mandatos e atividades parlamentares da Câmara.',
            longDescription: 'Legislatura é o nome dado ao período de trabalhos parlamentares entre uma eleição e outra. Este serviço retorna uma lista onde cada item contém informações básicas sobre um desses períodos. Se omitido, serão retornados dados sobre todas as legislaturas.',
            parameters: [
                { name: 'id', type: 'query', description: 'ID da legislatura.', autocomplete: 'legislaturas' },
                { name: 'data', type: 'query', description: 'Data (AAAA-MM-DD).'},
            ],
          },
          {
            id: 'getLegislaturaById',
            method: 'GET',
            path: '/legislaturas/{id}',
            description: 'Informações extras sobre uma determinada legislatura da Câmara.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico da legislatura.', required: true, autocomplete: 'legislaturas' },
            ],
          },
           {
            id: 'getLegislaturaMesa',
            method: 'GET',
            path: '/legislaturas/{id}/mesa',
            description: 'Deputados que fizeram parte da Mesa Diretora.',
            longDescription: 'Retorna uma lista com dados básicos sobre todos os deputados que ocuparam algum posto na Mesa Diretora da Câmara em algum período de tempo dentro da legislatura identificada por {id}.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico da legislatura.', required: true, autocomplete: 'legislaturas' },
            ],
          },
          {
            id: 'getLegislaturaLideres',
            method: 'GET',
            path: '/legislaturas/{id}/lideres',
            description: 'Retorna a lista de parlamentares que ocuparam cargos de liderança ao longo da legislatura.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID da legislatura.', required: true, autocomplete: 'legislaturas' },
            ],
          },
        ],
      },
      {
        name: 'Órgãos',
        icon: OrgansIcon,
        endpoints: [
          {
            id: 'getOrgaos',
            method: 'GET',
            path: '/orgaos',
            description: 'A lista das comissões e outros órgãos legislativos da Câmara.',
            longDescription: 'Se nenhum parâmetro for passado, são retornados dados sobre todos os órgãos que estão em funcionamento no momento da requisição.',
            parameters: [
              { name: 'sigla', type: 'query', description: 'Sigla do órgão.'},
              { name: 'dataInicio', type: 'query', description: 'Data de início (AAAA-MM-DD).'},
              { name: 'dataFim', type: 'query', description: 'Data de fim (AAAA-MM-DD).'},
            ],
          },
          {
            id: 'getOrgaoById',
            method: 'GET',
            path: '/orgaos/{id}',
            description: 'Informações detalhadas sobre um órgão da Câmara.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico do órgão.', required: true, autocomplete: 'orgaos' },
            ],
          },
          {
            id: 'getOrgaoEventos',
            method: 'GET',
            path: '/orgaos/{id}/eventos',
            description: 'Eventos ocorridos ou previstos em um órgão.',
            longDescription: 'Por padrão, são retornados eventos em andamento ou previstos para o mesmo dia, dois dias antes e dois dias depois da requisição.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico do órgão.', required: true, autocomplete: 'orgaos' },
            ],
          },
          {
            id: 'getOrgaoMembros',
            method: 'GET',
            path: '/orgaos/{id}/membros',
            description: 'Lista de parlamentares que ocupam cargos em um órgão.',
            longDescription: 'Se não forem passados parâmetros para delimitar este período, o serviço retorna os membros do órgão no momento da requisição.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico do órgão.', required: true, autocomplete: 'orgaos' },
            ],
          },
          {
            id: 'getOrgaoVotacoes',
            method: 'GET',
            path: '/orgaos/{id}/votacoes',
            description: 'Votações de um órgão.',
            longDescription: 'Retorna uma lista de dados básicos de votações que tenham sido realizadas em eventos realizados no órgão {id}.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico do órgão.', required: true, autocomplete: 'orgaos' },
            ],
          },
        ],
      },
      {
        name: 'Eventos',
        icon: EventsIcon,
        endpoints: [
          {
            id: 'getEventos',
            method: 'GET',
            path: '/eventos',
            description: 'Lista de eventos ocorridos ou previstos nos diversos órgãos da Câmara.',
            longDescription: 'Este intervalo pode ser configurado pelos parâmetros de data e hora listados abaixo. Se nenhum for passado, são listados eventos dos cinco dias anteriores, dos cinco dias seguintes e do próprio dia em que é feita a requisição.',
            parameters: [
                 { name: 'dataInicio', type: 'query', description: 'Data de início (AAAA-MM-DD).' },
                { name: 'dataFim', type: 'query', description: 'Data de fim (AAAA-MM-DD).' },
                { name: 'idOrgao', type: 'query', description: 'ID do órgão.', autocomplete: 'orgaos'},
            ],
          },
          {
            id: 'getEventoById',
            method: 'GET',
            path: '/eventos/{id}',
            description: 'Informações detalhadas sobre um evento específico.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico do evento.', required: true, autocomplete: 'eventos' },
            ],
          },
          {
            id: 'getEventoDeputados',
            method: 'GET',
            path: '/eventos/{id}/deputados',
            description: 'Deputados participantes de um evento.',
            longDescription: 'Se o evento ainda não ocorreu, a lista mostra os deputados que devem participar do evento, por serem convidados ou por serem membros do(s) órgão(s) responsável pelo evento.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico do evento.', required: true, autocomplete: 'eventos' },
            ],
          },
          {
            id: 'getEventoOrgaos',
            method: 'GET',
            path: '/eventos/{id}/orgaos',
            description: 'Lista os órgãos responsáveis pela organização de um evento.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico do evento.', required: true, autocomplete: 'eventos' },
            ],
          },
          {
            id: 'getEventoPauta',
            method: 'GET',
            path: '/eventos/{id}/pauta',
            description: 'Retorna a lista de proposições que foram ou serão avaliadas em um evento.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico do evento.', required: true, autocomplete: 'eventos' },
            ],
          },
           {
            id: 'getEventoVotacoes',
            method: 'GET',
            path: '/eventos/{id}/votacoes',
            description: 'Votações sobre um evento específico.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico do evento.', required: true, autocomplete: 'eventos' },
            ],
          },
        ],
      },
      {
        name: 'Blocos',
        icon: BlocosIcon,
        endpoints: [
          {
            id: 'getBlocos',
            method: 'GET',
            path: '/blocos',
            description: 'Lista os blocos partidários formados em uma legislatura.',
            longDescription: 'Nas atividades parlamentares, partidos podem se juntar em blocos partidários. Este recurso é uma lista dos blocos em atividade no momento da requisição.',
            parameters: [
              { name: 'id', type: 'query', description: 'ID do bloco (separados por vírgula).', autocomplete: 'blocos' },
              { name: 'idLegislatura', type: 'query', description: 'ID da legislatura (separados por vírgula).', autocomplete: 'legislaturas' },
            ],
          },
          {
            id: 'getBlocoById',
            method: 'GET',
            path: '/blocos/{id}',
            description: 'Retorna informações sobre um bloco partidário específico.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico do bloco.', required: true, autocomplete: 'blocos' },
            ],
          },
          {
            id: 'getBlocoPartidos',
            method: 'GET',
            path: '/blocos/{id}/partidos',
            description: 'Lista os partidos que compõem um bloco.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico do bloco.', required: true, autocomplete: 'blocos' },
            ],
          },
        ],
      },
      {
        name: 'Grupos',
        icon: GruposIcon,
        endpoints: [
          {
            id: 'getGrupos',
            method: 'GET',
            path: '/grupos',
            description: 'Lista os grupos de cooperação interparlamentar.',
            longDescription: 'Este endpoint retorna uma lista em que cada item representa um dos grupos interparlamentares em que a Câmara teve representantes.',
            parameters: [],
          },
          {
            id: 'getGrupoById',
            method: 'GET',
            path: '/grupos/{id}',
            description: 'Fornece informações detalhadas sobre um grupo interparlamentar.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico do grupo.', required: true, autocomplete: 'grupos' },
            ],
          },
          {
            id: 'getGrupoHistorico',
            method: 'GET',
            path: '/grupos/{id}/historico',
            description: 'Apresenta o histórico de mudanças de estado de um grupo.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico do grupo.', required: true, autocomplete: 'grupos' },
            ],
          },
          {
            id: 'getGrupoMembros',
            method: 'GET',
            path: '/grupos/{id}/membros',
            description: 'Lista os parlamentares que integram um grupo.',
            longDescription: 'Se nenhum parâmetro de tempo for utilizado, são retornados os integrantes registrados no momento da requisição. A lista estará vazia se o grupo {id} ainda não tiver sido instalado na legislatura atual.',
            parameters: [
              { name: 'id', type: 'path', description: 'ID numérico do grupo.', required: true, autocomplete: 'grupos' },
            ],
          },
        ],
      },
      {
        name: 'Referências',
        icon: ReferencesIcon,
        endpoints: [
          {
            id: 'getReferenciasUF',
            method: 'GET',
            path: '/referencias/uf',
            description: 'Lista de siglas de Unidades Federativas (UF) e seus códigos.',
            longDescription: 'Retorna uma lista de siglas e nomes das unidades de federação brasileiras, usados principalmente para indicar onde um parlamentar foi eleito.',
            parameters: [],
          },
          {
            id: 'getReferenciasSituacaoDeputado',
            method: 'GET',
            path: '/referencias/situacoesDeputado',
            description: 'Lista das possíveis situações de exercício parlamentar de um deputado.',
            parameters: [],
          },
          {
            id: 'getReferenciasTiposProposicao',
            method: 'GET',
            path: '/referencias/proposicoes/siglaTipo',
            description: 'Lista dos tipos de proposição legislativa e seus códigos.',
            parameters: [],
          },
          {
            id: 'getReferenciasTiposOrgao',
            method: 'GET',
            path: '/referencias/tiposOrgao',
            description: 'Lista dos tipos de órgãos da Câmara, como comissões e bancadas.',
            parameters: [],
          },
           {
            id: 'getReferenciasSituacoesEvento',
            method: 'GET',
            path: '/referencias/situacoesEvento',
            description: 'Lista os tipos de presença que podem ser registrados para um deputado em um evento.',
            parameters: [],
          },
          {
            id: 'getReferenciasTiposEvento',
            method: 'GET',
            path: '/referencias/tiposEvento',
            description: 'Lista os tipos de eventos que podem ocorrer na Câmara.',
            parameters: [],
          },
          {
            id: 'getReferenciasSituacoesProposicao',
            method: 'GET',
            path: '/referencias/situacoesProposicao',
            description: 'Lista as possíveis situações de tramitação de uma proposição.',
            parameters: [],
          },
          {
            id: 'getReferenciasTemasProposicao',
            method: 'GET',
            path: '/referencias/proposicoes/codTema',
            description: 'Lista os temas que podem ser associados a uma proposição.',
            parameters: [],
          },
          {
            id: 'getReferenciasDeputados',
            method: 'GET',
            path: '/referencias/deputados',
            description: 'Agrega todos os valores válidos para os parâmetros do endpoint /deputados.',
            parameters: [],
          },
          {
            id: 'getReferenciasCodSituacaoDeputado',
            method: 'GET',
            path: '/referencias/deputados/codSituacao',
            description: 'Retorna as possíveis situações de exercício parlamentar de um deputado.',
            parameters: [],
          },
          {
            id: 'getReferenciasCodTipoProfissao',
            method: 'GET',
            path: '/referencias/deputados/codTipoProfissao',
            description: 'Fornece os códigos e títulos das profissões declaradas pelos deputados.',
            parameters: [],
          },
          {
            id: 'getReferenciasTipoDespesa',
            method: 'GET',
            path: '/referencias/deputados/tipoDespesa',
            description: 'Lista os tipos de despesas que compõem a Cota Parlamentar.',
            parameters: [],
          },
          {
            id: 'getReferenciasEventos',
            method: 'GET',
            path: '/referencias/eventos',
            description: 'Agrega todos os valores válidos para os parâmetros do endpoint /eventos.',
            parameters: [],
          },
          {
            id: 'getReferenciasCodSituacaoEvento',
            method: 'GET',
            path: '/referencias/eventos/codSituacaoEvento',
            description: 'Retorna os códigos das possíveis situações para eventos.',
            parameters: [],
          },
          {
            id: 'getReferenciasCodTipoEvento',
            method: 'GET',
            path: '/referencias/eventos/codTipoEvento',
            description: 'Retorna os códigos dos tipos de eventos realizados na Câmara.',
            parameters: [],
          },
          {
            id: 'getReferenciasOrgaos',
            method: 'GET',
            path: '/referencias/orgaos',
            description: 'Agrega todos os valores válidos para os parâmetros do endpoint /orgaos.',
            parameters: [],
          },
          {
            id: 'getReferenciasCodSituacaoOrgao',
            method: 'GET',
            path: '/referencias/orgaos/codSituacao',
            description: 'Lista as situações em que um órgão pode se encontrar.',
            parameters: [],
          },
           {
            id: 'getReferenciasCodTipoOrgao',
            method: 'GET',
            path: '/referencias/orgaos/codTipoOrgao',
            description: 'Retorna os códigos dos tipos de órgãos que existem na Câmara.',
            parameters: [],
          },
          {
            id: 'getReferenciasSituacoesOrgao',
            method: 'GET',
            path: '/referencias/situacoesOrgao',
            description: 'Lista as situações em que um órgão pode se encontrar.',
            parameters: [],
          },
          {
            id: 'getReferenciasProposicoes',
            method: 'GET',
            path: '/referencias/proposicoes',
            description: 'Agrega todos os valores válidos para os parâmetros do endpoint /proposicoes.',
            parameters: [],
          },
          {
            id: 'getReferenciasCodSituacaoProposicao',
            method: 'GET',
            path: '/referencias/proposicoes/codSituacao',
            description: 'Retorna os códigos dos possíveis estados de tramitação de uma proposição.',
            parameters: [],
          },
          {
            id: 'getReferenciasCodTipoAutor',
            method: 'GET',
            path: '/referencias/proposicoes/codTipoAutor',
            description: 'Lista os tipos de entidades que podem ser autoras de proposições.',
            parameters: [],
          },
          {
            id: 'getReferenciasCodTipoTramitacao',
            method: 'GET',
            path: '/referencias/proposicoes/codTipoTramitacao',
            description: 'Apresenta os tipos de tramitação existentes.',
            parameters: [],
          },
          {
            id: 'getReferenciasTiposAutor',
            method: 'GET',
            path: '/referencias/tiposAutor',
            description: 'Lista os tipos de entidades que podem ser autoras de proposições.',
            parameters: [],
          },
          {
            id: 'getReferenciasTiposTramitacao',
            method: 'GET',
            path: '/referencias/tiposTramitacao',
            description: 'Lista os vários tipos de tramitação existentes.',
            parameters: [],
          },
        ],
      },
    ]
  },
  {
    name: 'Senado',
    baseUrl: 'https://legis.senado.leg.br/dadosabertos',
    icon: SenadoIcon,
    categories: [
      {
        name: 'Comissão',
        icon: OrgansIcon,
        description: 'Informações de Comissões, Órgãos, Conselhos e demais Colegiados do Senado Federal e Congresso Nacional.',
        endpoints: [
          {
            id: 'getComissaoByCodigo',
            method: 'GET',
            path: '/comissao/{codigo}',
            description: 'Detalhes de um Colegiado do Congresso Nacional.',
            parameters: [{ name: 'codigo', type: 'path', description: 'Código do colegiado. Comece a digitar para buscar.', required: true, autocomplete: 'senado_comissoes_codigo' }],
          },
          {
            id: 'getComissaoAgendaByDateRange',
            method: 'GET',
            path: '/comissao/agenda/{dataInicio}/{dataFim}',
            description: 'Agenda das Reuniões de Comissão por período.',
            parameters: [
              { name: 'dataInicio', type: 'path', description: 'Data de início (YYYYMMDD).', required: true },
              { name: 'dataFim', type: 'path', description: 'Data de fim (YYYYMMDD).', required: true },
            ],
          },
          {
            id: 'getComissaoAgendaByDate',
            method: 'GET',
            path: '/comissao/agenda/{dataReferencia}',
            description: 'Agenda das Reuniões de Comissão em uma data específica.',
            parameters: [{ name: 'dataReferencia', type: 'path', description: 'Data de referência (YYYYMMDD).', required: true }],
          },
          {
            id: 'getComissaoAgendaAtualICal',
            method: 'GET',
            path: '/comissao/agenda/atual/iCal',
            description: 'Obtém a Agenda das Comissões dos próximos 30 dias (Formato iCal).',
            parameters: [],
            responseType: 'ical',
          },
          {
            id: 'getComissaoAgendaByMonth',
            method: 'GET',
            path: '/comissao/agenda/mes/{mesReferencia}',
            description: 'Agenda das Reuniões de Comissão no mês informado.',
            parameters: [{ name: 'mesReferencia', type: 'path', description: 'Mês de referência (MMYYYY).', required: true }],
          },
          {
            id: 'getComissaoCpiRequerimentos',
            method: 'GET',
            path: '/comissao/cpi/{comissao}/requerimentos',
            description: 'Lista Requerimentos de CPI. Exclusivo para CPIs.',
            parameters: [{ name: 'comissao', type: 'path', description: 'Sigla da comissão CPI. Comece a digitar para buscar.', required: true, autocomplete: 'senado_comissoes_sigla' }],
          },
          {
            id: 'getComissaoListaPorTipo',
            method: 'GET',
            path: '/comissao/lista/{tipo}',
            description: 'Lista de Colegiados do Senado Federal (por tipo).',
            parameters: [{ name: 'tipo', type: 'path', description: 'Tipo do colegiado.', required: true }],
          },
          {
            id: 'getComissaoListaColegiados',
            method: 'GET',
            path: '/comissao/lista/colegiados',
            description: 'Obtém a Lista geral de Colegiados em atividade no Congresso Nacional.',
            parameters: [],
          },
          {
            id: 'getComissaoListaMistas',
            method: 'GET',
            path: '/comissao/lista/mistas',
            description: 'Comissões Mistas atuais do Congresso Nacional.',
            parameters: [],
          },
          {
            id: 'getComissaoListaTiposColegiado',
            method: 'GET',
            path: '/comissao/lista/tiposColegiado',
            description: 'Obtém a Lista de Tipos de Colegiado do Senado Federal e Congresso Nacional.',
            parameters: [],
          },
          {
            id: 'getComissaoReuniaoByCodigo',
            method: 'GET',
            path: '/comissao/reuniao/{codigoReuniao}',
            description: 'Informações detalhadas da Reunião de Comissão.',
            parameters: [{ name: 'codigoReuniao', type: 'path', description: 'Código da reunião. Pode ser obtido nos endpoints de agenda.', required: true }],
          },
          {
            id: 'getComissaoReuniaoDocumento',
            method: 'GET',
            path: '/comissao/reuniao/{sigla}/documento/{tipoDocumento}',
            description: 'Link para um documento da última Reunião de uma Comissão.',
            parameters: [
              { name: 'sigla', type: 'path', description: 'Sigla da comissão (Ex: CAE). Comece a digitar para buscar.', required: true, autocomplete: 'senado_comissoes_sigla' },
              { name: 'tipoDocumento', type: 'path', description: 'Tipo do documento.', required: true, options: ['pauta', 'pautacheia', 'resultado'] },
            ],
            responseType: 'text',
          },
          {
            id: 'getComissaoReuniaoNotas',
            method: 'GET',
            path: '/comissao/reuniao/notas/{codigoReuniao}',
            description: 'Notas Taquigráficas da Reunião de Comissão.',
            parameters: [{ name: 'codigoReuniao', type: 'path', description: 'Código da reunião. Pode ser obtido nos endpoints de agenda.', required: true }],
          },
        ],
      },
      {
        name: 'Composição',
        icon: BlocosIcon,
        description: 'Composição dos Parlamentares no Senado e no Congresso.',
        endpoints: [
          {
            id: 'getComposicaoBlocoByCodigo',
            method: 'GET',
            path: '/composicao/bloco/{codigo}',
            description: 'Composição de um Bloco Parlamentar.',
            parameters: [
                { name: 'codigo', type: 'path', description: 'Código do Bloco. Comece a digitar para buscar.', required: true, autocomplete: 'senado_blocos' },
                { name: 'v', type: 'query', description: 'Versão do serviço.'}
            ],
          },
          {
            id: 'getComposicaoComissaoByCodigo',
            method: 'GET',
            path: '/composicao/comissao/{codigo}',
            description: 'Última Composição de uma Comissão do Senado Federal.',
            parameters: [
                { name: 'codigo', type: 'path', description: 'Código da comissão. Comece a digitar para buscar.', required: true, autocomplete: 'senado_comissoes_codigo' },
                { name: 'ativas', type: 'query', description: 'Apenas vagas ativas (S). Para todas, não informe.', options: ['S'] },
                { name: 'v', type: 'query', description: 'Versão do serviço.'}
            ],
          },
          {
            id: 'getComposicaoComissaoAtualMistaByCodigo',
            method: 'GET',
            path: '/composicao/comissao/atual/mista/{codigo}',
            description: 'Composição atual de uma Comissão Mista.',
            parameters: [
                { name: 'codigo', type: 'path', description: 'Código da comissão mista. Comece a digitar para buscar.', required: true, autocomplete: 'senado_comissoes_codigo' },
                { name: 'v', type: 'query', description: 'Versão do serviço.'}
            ],
          },
          {
            id: 'getComposicaoComissaoResumidaMista',
            method: 'GET',
            path: '/composicao/comissao/resumida/mista/{codigo}/{dataInicio}/{dataFim}',
            description: 'Composição resumida de uma Comissão Mista em determinado período.',
            parameters: [
              { name: 'codigo', type: 'path', description: 'Código da comissão mista. Comece a digitar para buscar.', required: true, autocomplete: 'senado_comissoes_codigo' },
              { name: 'dataInicio', type: 'path', description: 'Data de início (YYYYMMDD).', required: true },
              { name: 'dataFim', type: 'path', description: 'Data de fim (YYYYMMDD).', required: true },
              { name: 'v', type: 'query', description: 'Versão do serviço.'}
            ],
          },
          {
            id: 'getComposicaoLideranca',
            method: 'GET',
            path: '/composicao/lideranca',
            description: 'Lista Lideranças do Senado Federal, Congresso Nacional e Câmara dos Deputados.',
            parameters: [
                { name: 'codigo', type: 'query', description: 'Código da liderança.' },
                { name: 'casa', type: 'query', description: 'Casa da liderança (CN, CD ou SF).', options: ['CN', 'CD', 'SF'] },
                { name: 'idTipoUnidadeLideranca', type: 'query', description: 'ID do tipo de unidade de liderança.' },
                { name: 'codigoParlamentar', type: 'query', description: 'Código do parlamentar.', autocomplete: 'senado_parlamentar' },
                { name: 'vigente', type: 'query', description: "Situação: 'S'-Vigentes, 'N'-Encerradas, Em branco-Todas.", options: ['S', 'N'] },
                { name: 'dataInicio', type: 'query', description: 'Lideranças a partir desta data (AAAA-MM-DD).' },
                { name: 'dataFim', type: 'query', description: 'Lideranças até esta data (AAAA-MM-DD).' },
                { name: 'siglaTipoLideranca', type: 'query', description: 'Sigla do tipo de liderança.' },
                { name: 'codigoPartido', type: 'query', description: 'Código do partido. Comece a digitar para buscar.', autocomplete: 'senado_partidos' },
                { name: 'codigoBloco', type: 'query', description: 'Código do bloco. Comece a digitar para buscar.', autocomplete: 'senado_blocos' },
                { name: 'v', type: 'query', description: 'Versão do serviço.' },
            ],
          },
          {
            id: 'getComposicaoLiderancaTipos',
            method: 'GET',
            path: '/composicao/lideranca/tipos',
            description: 'Lista Tipos de Lideranças.',
            parameters: [
                { name: 'v', type: 'query', description: 'Versão do serviço.'}
            ],
          },
          {
            id: 'getComposicaoLiderancaTiposUnidade',
            method: 'GET',
            path: '/composicao/lideranca/tipos-unidade',
            description: 'Lista Tipos de Unidades de Lideranças.',
            parameters: [
                { name: 'v', type: 'query', description: 'Versão do serviço.'}
            ],
          },
          {
            id: 'getComposicaoListaByTipo',
            method: 'GET',
            path: '/composicao/lista/{tipo}',
            description: 'Obtém a Composição das Comissões do Senado Federal por tipo de Colegiado.',
            parameters: [{ name: 'tipo', type: 'path', description: 'Tipo do colegiado.', required: true, options: ['permanente', 'temporaria', 'cpi', 'cpmi', 'grupo', 'conselho', 'outros'] }],
          },
          {
            id: 'getComposicaoListaBlocos',
            method: 'GET',
            path: '/composicao/lista/blocos',
            description: 'Obtém a lista e a Composição dos Blocos Parlamentares no Senado Federal.',
            parameters: [],
          },
          {
            id: 'getComposicaoListaCNByTipo',
            method: 'GET',
            path: '/composicao/lista/cn/{tipo}',
            description: 'Composição das Comissões do Congresso Nacional por tipo.',
            parameters: [
                { name: 'tipo', type: 'path', description: 'Tipo de comissão.', required: true, options: ['cpmi', 'veto', 'permanente', 'mpv', 'mistaEspecial', 'mesa', 'trabalhoCCS', 'representativa'] },
                { name: 'v', type: 'query', description: 'Versão do serviço.'}
            ],
          },
          {
            id: 'getComposicaoListaPartidos',
            method: 'GET',
            path: '/composicao/lista/partidos',
            description: 'Obtém a lista dos Partidos Políticos em atividade e/ou extintos no Senado Federal.',
            parameters: [],
          },
          {
            id: 'getComposicaoListaTiposCargo',
            method: 'GET',
            path: '/composicao/lista/tiposCargo',
            description: 'Obtém a lista de Tipos de Cargo nas Comissões do Senado Federal e Congresso Nacional.',
            parameters: [],
          },
          {
            id: 'getComposicaoMesaCN',
            method: 'GET',
            path: '/composicao/mesaCN',
            description: 'Obtém a Composição dos integrantes da Mesa Diretora do Congresso Nacional.',
            parameters: [],
          },
          {
            id: 'getComposicaoMesaSF',
            method: 'GET',
            path: '/composicao/mesaSF',
            description: 'Obtém a Composição dos integrantes da Mesa Diretora do Senado Federal.',
            parameters: [],
          },
        ],
      },
      {
        name: 'Discurso',
        icon: DiscursoIcon,
        description: 'Pronunciamentos de Senadores e notas taquigráficas com links dos vídeos gravados das Sessões Plenárias e Reuniões de Comissão.',
        endpoints: [
            {
                id: 'getDiscursoTextoBinario',
                method: 'GET',
                path: '/discurso/texto-binario/{codigoPronunciamento}',
                description: 'Texto Integral de um Pronunciamento em formato binário.',
                parameters: [{ name: 'codigoPronunciamento', type: 'path', description: 'Código do Pronunciamento.', required: true }],
                responseType: 'text',
            },
            {
                id: 'getDiscursoTextoIntegral',
                method: 'GET',
                path: '/discurso/texto-integral/{codigoPronunciamento}',
                description: 'Texto Integral de um Pronunciamento em formato texto plano (txt).',
                parameters: [{ name: 'codigoPronunciamento', type: 'path', description: 'Código do Pronunciamento.', required: true }],
                responseType: 'text',
            },
            {
                id: 'getPlenarioListaDiscursos',
                method: 'GET',
                path: '/plenario/lista/discursos/{dataInicio}/{dataFim}',
                description: 'Lista Discursos das Sessões que ocorreram dentro do período informado (máximo de 30 dias).',
                parameters: [
                  { name: 'dataInicio', type: 'path', description: 'Data de início (YYYYMMDD).', required: true },
                  { name: 'dataFim', type: 'path', description: 'Data de fim (YYYYMMDD).', required: true },
                  { name: 'siglaCasa', type: 'query', description: 'Sigla da casa (SF ou CN).', options: ['SF', 'CN'] },
                  { name: 'tipoSessao', type: 'query', description: 'Sigla do tipo de Sessão.', options: ['DOR', 'DEX', 'SDE', 'SDT', 'SND', 'SSN', 'SES', 'RCN'] },
                  { name: 'numeroSessao', type: 'query', description: 'Número da Sessão.' },
                  { name: 'v', type: 'query', description: 'Versão do serviço.' }
                ],
            },
            {
                id: 'getSenadorApartes',
                method: 'GET',
                path: '/senador/{codigo}/apartes',
                description: 'Apartes feitos por um Senador.',
                parameters: [
                  { name: 'codigo', type: 'path', description: 'Código do Senador.', required: true, autocomplete: 'senado_parlamentar' },
                  { name: 'casa', type: 'query', description: 'Sigla da Casa onde ocorre o pronunciamento.', options: ['SF', 'CD', 'CN', 'PR', 'CR', 'AC'] },
                  { name: 'dataInicio', type: 'query', description: 'Data de início (YYYYMMDD).' },
                  { name: 'dataFim', type: 'query', description: 'Data de fim (YYYYMMDD).' },
                  { name: 'numeroSessao', type: 'query', description: 'Número da Sessão Plenária.' },
                  { name: 'tipoSessao', type: 'query', description: 'Tipo da Sessão Plenária.', options: ['DOR', 'DEX', 'SDE', 'SDT', 'SND', 'SSN', 'SES', 'RCN'] },
                  { name: 'v', type: 'query', description: 'Versão do serviço.' }
                ],
            },
            {
                id: 'getSenadorDiscursos',
                method: 'GET',
                path: '/senador/{codigo}/discursos',
                description: 'Discursos de um Senador.',
                parameters: [
                  { name: 'codigo', type: 'path', description: 'Código do Senador.', required: true, autocomplete: 'senado_parlamentar' },
                  { name: 'casa', type: 'query', description: 'Sigla da Casa onde ocorre o pronunciamento.', options: ['SF', 'CD', 'CN', 'PR', 'CR', 'AC'] },
                  { name: 'dataInicio', type: 'query', description: 'Data de início (YYYYMMDD).' },
                  { name: 'dataFim', type: 'query', description: 'Data de fim (YYYYMMDD).' },
                  { name: 'numeroSessao', type: 'query', description: 'Número da Sessão Plenária.' },
                  { name: 'tipoSessao', type: 'query', description: 'Tipo da Sessão Plenária.', options: ['DOR', 'DEX', 'SDE', 'SDT', 'SND', 'SSN', 'SES', 'RCN'] },
                  { name: 'v', type: 'query', description: 'Versão do serviço.' }
                ],
            },
            {
                id: 'getSenadorTiposUsoPalavra',
                method: 'GET',
                path: '/senador/lista/tiposUsoPalavra',
                description: 'Lista os Tipos de Uso da Palavra (Modalidades de Discursos).',
                parameters: [],
            },
            {
                id: 'getTaquigrafiaNotasReuniao',
                method: 'GET',
                path: '/taquigrafia/notas/reuniao/{idReuniao}',
                description: 'Notas Taquigráficas de Reuniões de Comissão e/ou outros Colegiados.',
                parameters: [
                  { name: 'idReuniao', type: 'path', description: 'Código do Encontro Legislativo (Reunião de Colegiado).', required: true },
                  { name: 'v', type: 'query', description: 'Versão do serviço.' }
                ],
            },
            {
                id: 'getTaquigrafiaNotasSessao',
                method: 'GET',
                path: '/taquigrafia/notas/sessao/{idSessao}',
                description: 'Notas Taquigráficas de Sessões Plenárias.',
                parameters: [
                  { name: 'idSessao', type: 'path', description: 'Código do Encontro Legislativo (Sessão Plenária).', required: true },
                  { name: 'v', type: 'query', description: 'Versão do serviço.' }
                ],
            },
            {
                id: 'getTaquigrafiaVideosReuniao',
                method: 'GET',
                path: '/taquigrafia/videos/reuniao/{idReuniao}',
                description: 'Unidades Descritivas (vídeos) de Reuniões de Comissão e/ou outros Colegiados.',
                parameters: [
                  { name: 'idReuniao', type: 'path', description: 'Código do Encontro Legislativo (Reunião de Colegiado).', required: true },
                  { name: 'v', type: 'query', description: 'Versão do serviço.' }
                ],
            },
            {
                id: 'getTaquigrafiaVideosSessao',
                method: 'GET',
                path: '/taquigrafia/videos/sessao/{idSessao}',
                description: 'Unidades Descritivas (vídeos) de Sessões Plenárias.',
                parameters: [
                  { name: 'idSessao', type: 'path', description: 'Código do Encontro Legislativo (Sessão Plenária).', required: true },
                  { name: 'v', type: 'query', description: 'Versão do serviço.' }
                ],
            },
        ],
      },
      {
        name: 'Parlamentar',
        icon: ParlamentarIcon,
        description: 'Informações de Senadores e Deputados Federais, Exercícios, Mandatos, Lideranças, etc.',
        endpoints: [
            {
                id: 'getSenadorByCodigo',
                method: 'GET',
                path: '/senador/{codigo}',
                description: 'Obtém informações de um Senador.',
                parameters: [{ name: 'codigo', type: 'path', description: 'Código do Senador.', required: true, autocomplete: 'senado_parlamentar' }],
            },
            {
                id: 'getSenadorCargos',
                method: 'GET',
                path: '/senador/{codigo}/cargos',
                description: 'Obtém a relação de Cargos ocupados por um Senador.',
                parameters: [{ name: 'codigo', type: 'path', description: 'Código do Senador.', required: true, autocomplete: 'senado_parlamentar' }],
            },
            {
                id: 'getSenadorComissoes',
                method: 'GET',
                path: '/senador/{codigo}/comissoes',
                description: 'Obtém a relação das Comissões que um Senador é membro.',
                parameters: [{ name: 'codigo', type: 'path', description: 'Código do Senador.', required: true, autocomplete: 'senado_parlamentar' }],
            },
            {
                id: 'getSenadorFiliacoes',
                method: 'GET',
                path: '/senador/{codigo}/filiacoes',
                description: 'Obtém as Filiações Partidárias de um Senador.',
                parameters: [{ name: 'codigo', type: 'path', description: 'Código do Senador.', required: true, autocomplete: 'senado_parlamentar' }],
            },
            {
                id: 'getSenadorHistoricoAcademico',
                method: 'GET',
                path: '/senador/{codigo}/historicoAcademico',
                description: 'Obtém o Histórico Acadêmico de um Senador.',
                parameters: [{ name: 'codigo', type: 'path', description: 'Código do Senador.', required: true, autocomplete: 'senado_parlamentar' }],
            },
            {
                id: 'getSenadorLicencas',
                method: 'GET',
                path: '/senador/{codigo}/licencas',
                description: 'Obtém as Licenças oficiais de um Senador.',
                parameters: [{ name: 'codigo', type: 'path', description: 'Código do Senador.', required: true, autocomplete: 'senado_parlamentar' }],
            },
            {
                id: 'getSenadorMandatos',
                method: 'GET',
                path: '/senador/{codigo}/mandatos',
                description: 'Obtém os Mandatos Parlamentares de um Senador.',
                parameters: [{ name: 'codigo', type: 'path', description: 'Código do Senador.', required: true, autocomplete: 'senado_parlamentar' }],
            },
            {
                id: 'getSenadorProfissao',
                method: 'GET',
                path: '/senador/{codigo}/profissao',
                description: 'Obtém as Profissões de um Senador.',
                parameters: [{ name: 'codigo', type: 'path', description: 'Código do Senador.', required: true, autocomplete: 'senado_parlamentar' }],
            },
            {
                id: 'getSenadorAfastados',
                method: 'GET',
                path: '/senador/afastados',
                description: 'Obtém a lista dos Senadores atualmente afastados (Fora de Exercício).',
                parameters: [],
            },
            {
                id: 'getSenadorListaAtual',
                method: 'GET',
                path: '/senador/lista/atual',
                description: 'Senadores em Exercício.',
                parameters: [],
            },
            {
                id: 'getSenadorListaPorLegislatura',
                method: 'GET',
                path: '/senador/lista/legislatura/{legislatura}',
                description: 'Obtém a lista de Senadores de uma determinada Legislatura.',
                parameters: [{ name: 'legislatura', type: 'path', description: 'Número da legislatura.', required: true }],
            },
            {
                id: 'getSenadorListaPorIntervaloLegislatura',
                method: 'GET',
                path: '/senador/lista/legislatura/{legislaturaInicio}/{legislaturaFim}',
                description: 'Obtém a lista de Senadores de um intervalo de Legislaturas.',
                parameters: [
                    { name: 'legislaturaInicio', type: 'path', description: 'Número da legislatura inicial.', required: true },
                    { name: 'legislaturaFim', type: 'path', description: 'Número da legislatura final.', required: true },
                ],
            },
            {
                id: 'getSenadorPartidos',
                method: 'GET',
                path: '/senador/partidos',
                description: 'Lista os Partidos Políticos em atividade e/ou extintos.',
                parameters: [],
            },
        ],
      },
      {
        name: 'Plenário',
        icon: PlenarioIcon,
        description: 'Recursos relacionados aos Plenário do Senado e Congresso.',
        endpoints: [
            {
                id: 'getPlenarioAgendaAtualICal',
                method: 'GET',
                path: '/plenario/agenda/atual/iCal',
                description: 'Agenda de Plenário em formato iCal.',
                parameters: [],
                responseType: 'ical',
            },
            {
                id: 'getPlenarioAgendaCNDia',
                method: 'GET',
                path: '/plenario/agenda/cn/{data}',
                description: 'Agenda do dia do Plenário do Congresso Nacional.',
                parameters: [{ name: 'data', type: 'path', description: 'Data (YYYYMMDD).', required: true }],
            },
            {
                id: 'getPlenarioAgendaCNPeriodo',
                method: 'GET',
                path: '/plenario/agenda/cn/{inicio}/{fim}',
                description: 'Agenda do período do Plenário do Congresso Nacional.',
                parameters: [
                    { name: 'inicio', type: 'path', description: 'Data de início (YYYYMMDD).', required: true },
                    { name: 'fim', type: 'path', description: 'Data de fim (YYYYMMDD).', required: true },
                ],
            },
            {
                id: 'getPlenarioAgendaDia',
                method: 'GET',
                path: '/plenario/agenda/dia/{data}',
                description: 'Agenda do dia nos Plenários do Senado Federal e Congresso Nacional.',
                parameters: [{ name: 'data', type: 'path', description: 'Data (YYYYMMDD).', required: true }],
            },
            {
                id: 'getPlenarioAgendaMes',
                method: 'GET',
                path: '/plenario/agenda/mes/{data}',
                description: 'Agenda do mês nos Plenários do Senado Federal e Congresso Nacional.',
                parameters: [{ name: 'data', type: 'path', description: 'Data (MMYYYY).', required: true }],
            },
            {
                id: 'getPlenarioEncontroDetalhes',
                method: 'GET',
                path: '/plenario/encontro/{codigo}',
                description: 'Detalhes do Encontro Legislativo.',
                parameters: [{ name: 'codigo', type: 'path', description: 'Código do encontro.', required: true }],
            },
            {
                id: 'getPlenarioEncontroPauta',
                method: 'GET',
                path: '/plenario/encontro/{codigo}/pauta',
                description: 'Itens de Pauta do Encontro Legislativo.',
                parameters: [{ name: 'codigo', type: 'path', description: 'Código do encontro.', required: true }],
            },
            {
                id: 'getPlenarioEncontroResultado',
                method: 'GET',
                path: '/plenario/encontro/{codigo}/resultado',
                description: 'Resultado de Pauta do Encontro Legislativo.',
                parameters: [{ name: 'codigo', type: 'path', description: 'Código do encontro.', required: true }],
            },
            {
                id: 'getPlenarioEncontroResumo',
                method: 'GET',
                path: '/plenario/encontro/{codigo}/resumo',
                description: 'Resumo do Encontro Legislativo.',
                parameters: [{ name: 'codigo', type: 'path', description: 'Código do encontro.', required: true }],
            },
            {
                id: 'getPlenarioLegislaturaPorData',
                method: 'GET',
                path: '/plenario/legislatura/{data}',
                description: 'Obtém a Legislatura na data informada e suas Sessões Legislativas.',
                parameters: [{ name: 'data', type: 'path', description: 'Data (YYYYMMDD).', required: true }],
            },
            {
                id: 'getPlenarioListaLegislaturas',
                method: 'GET',
                path: '/plenario/lista/legislaturas',
                description: 'Lista de todas as Legislaturas e suas Sessões Legislativas.',
                parameters: [],
            },
            {
                id: 'getPlenarioResultadoData',
                method: 'GET',
                path: '/plenario/resultado/{data}',
                description: 'Obtém o Resultado da Sessão Plenária na data informada.',
                parameters: [{ name: 'data', type: 'path', description: 'Data (YYYYMMDD).', required: true }],
            },
            {
                id: 'getPlenarioResultadoCNData',
                method: 'GET',
                path: '/plenario/resultado/cn/{data}',
                description: 'Resultado da Sessão Plenária do Congresso Nacional.',
                parameters: [{ name: 'data', type: 'path', description: 'Data (YYYYMMDD).', required: true }],
            },
            {
                id: 'getPlenarioResultadoMes',
                method: 'GET',
                path: '/plenario/resultado/mes/{data}',
                description: 'Resultado da Sessão Plenária do mês.',
                parameters: [{ name: 'data', type: 'path', description: 'Data (MMYYYY).', required: true }],
            },
            {
                id: 'getPlenarioTiposSessao',
                method: 'GET',
                path: '/plenario/tiposSessao',
                description: 'Lista os Tipos de Sessão Plenária.',
                parameters: [],
            },
        ],
      },
      {
        name: 'Votação',
        icon: VotesIcon,
        description: 'Votação das Matérias nas Comissões e Sessões Plenárias.',
        endpoints: [
            {
                id: 'getVotacaoTiposComparecimento',
                method: 'GET',
                path: '/plenario/lista/tiposComparecimento',
                description: 'Lista os Tipos de Comparecimento em Votações do Plenário.',
                parameters: [],
            },
            {
                id: 'getVotacaoPlenarioResultadoVeto',
                method: 'GET',
                path: '/plenario/resultado/veto/{codigo}',
                description: 'Resultado da Votação Nominal de Veto.',
                parameters: [{ name: 'codigo', type: 'path', description: 'Código da matéria.', required: true }],
            },
            {
                id: 'getVotacaoPlenarioResultadoVetoDispositivo',
                method: 'GET',
                path: '/plenario/resultado/veto/dispositivo/{codigo}',
                description: 'Resultado da Votação Nominal de um Dispositivo do Veto (em Vetos Parciais).',
                parameters: [{ name: 'codigo', type: 'path', description: 'Código da matéria.', required: true }],
            },
            {
                id: 'getVotacaoPlenarioResultadoVetoMateria',
                method: 'GET',
                path: '/plenario/resultado/veto/materia/{codigo}',
                description: 'Resultado da Votação Nominal do Veto a um Projeto de Lei.',
                parameters: [{ name: 'codigo', type: 'path', description: 'Código da matéria.', required: true }],
            },
            {
                id: 'getVotacaoPlenarioOrientacaoBancadaPeriodo',
                method: 'GET',
                path: '/plenario/votacao/orientacaoBancada/{dataInicio}/{dataFim}',
                description: 'Orientação de Bancada para Votação de Matéria das Sessões que ocorreram em um período.',
                parameters: [
                    { name: 'dataInicio', type: 'path', description: 'Data de início (YYYYMMDD).', required: true },
                    { name: 'dataFim', type: 'path', description: 'Data de fim (YYYYMMDD).', required: true },
                ],
            },
            {
                id: 'getVotacaoPlenarioOrientacaoBancadaSessao',
                method: 'GET',
                path: '/plenario/votacao/orientacaoBancada/{dataSessao}',
                description: 'Orientação de Bancada para Votação de Matéria das Sessões que ocorreram em uma data.',
                parameters: [{ name: 'dataSessao', type: 'path', description: 'Data da sessão (YYYYMMDD).', required: true }],
            },
            {
                id: 'getVotacaoLista',
                method: 'GET',
                path: '/votacao',
                description: 'Votos Nominais de Parlamentares em Processos Legislativos.',
                parameters: [],
            },
            {
                id: 'getVotacaoComissaoPorComissao',
                method: 'GET',
                path: '/votacaoComissao/comissao/{siglaComissao}',
                description: 'Votações de Matérias nas Comissões do Senado Federal e Congresso Nacional.',
                parameters: [{ name: 'siglaComissao', type: 'path', description: 'Sigla da comissão.', required: true, autocomplete: 'senado_comissoes_sigla' }],
            },
            {
                id: 'getVotacaoComissaoPorMateria',
                method: 'GET',
                path: '/votacaoComissao/materia/{sigla}/{numero}/{ano}',
                description: 'Votações de Matérias nas Comissões por Identificação da Matéria.',
                parameters: [
                    { name: 'sigla', type: 'path', description: 'Sigla da matéria (e.g., PL).', required: true },
                    { name: 'numero', type: 'path', description: 'Número da matéria.', required: true },
                    { name: 'ano', type: 'path', description: 'Ano da matéria.', required: true },
                ],
            },
            {
                id: 'getVotacaoComissaoPorParlamentar',
                method: 'GET',
                path: '/votacaoComissao/parlamentar/{codigo}',
                description: 'Votações nas Comissões por Parlamentar.',
                parameters: [{ name: 'codigo', type: 'path', description: 'Código do parlamentar.', required: true, autocomplete: 'senado_parlamentar' }],
            },
        ],
      },
      {
        name: 'Processo e Matéria',
        icon: ProcessoIcon,
        description: 'Informações sobre Processos legislativos, Requerimentos e outras Matérias Legislativas.',
        endpoints: [
          {
            id: 'getAutorListaAtual',
            method: 'GET',
            path: '/autor/lista/atual',
            description: 'Lista Parlamentares Autores de Processos em tramitação.',
            parameters: [],
          },
          {
            id: 'getMateriaDistribuicaoAutoria',
            method: 'GET',
            path: '/materia/distribuicao/autoria',
            description: 'Distribuição de autoria de matérias (por comissão e/ou parlamentar).',
            parameters: [],
          },
          {
            id: 'getMateriaDistribuicaoAutoriaComissao',
            method: 'GET',
            path: '/materia/distribuicao/autoria/{siglaComissao}',
            description: 'Distribuição de autoria de matérias em uma comissão.',
            parameters: [{ name: 'siglaComissao', type: 'path', description: 'Sigla da comissão.', required: true, autocomplete: 'senado_comissoes_sigla' }],
          },
          {
            id: 'getMateriaDistribuicaoRelatoria',
            method: 'GET',
            path: '/materia/distribuicao/relatoria/{sigla}',
            description: 'Distribuição de relatoria de matérias em uma comissão.',
            parameters: [{ name: 'sigla', type: 'path', description: 'Sigla da comissão.', required: true, autocomplete: 'senado_comissoes_sigla' }],
          },
          {
            id: 'getMateriaListaTramitacao',
            method: 'GET',
            path: '/materia/lista/tramitacao',
            description: 'Total de Processos em tramitação por Tipo ou pelo Colegiado em que se encontra.',
            parameters: [],
          },
          {
            id: 'getMateriaVetosPorAno',
            method: 'GET',
            path: '/materia/vetos/{ano}',
            description: 'Relação de Vetos presidenciais por ano.',
            parameters: [{ name: 'ano', type: 'path', description: 'Ano.', required: true }],
          },
          {
            id: 'getMateriaVetosAntesRCN',
            method: 'GET',
            path: '/materia/vetos/antesrcn',
            description: 'Vetos anteriores à RCN 1/2013 em tramitação.',
            parameters: [],
          },
          {
            id: 'getMateriaVetosAposRCN',
            method: 'GET',
            path: '/materia/vetos/aposrcn',
            description: 'Vetos posteriores à RCN 1/2013 em tramitação.',
            parameters: [],
          },
          {
            id: 'getMateriaVetosEncerrados',
            method: 'GET',
            path: '/materia/vetos/encerrados',
            description: 'Vetos com tramitação encerrada.',
            parameters: [],
          },
          {
            id: 'getProcessoLista',
            method: 'GET',
            path: '/processo',
            description: 'Lista Processos Legislativos.',
            parameters: [],
          },
          {
            id: 'getProcessoById',
            method: 'GET',
            path: '/processo/{id}',
            description: 'Detalhes de um Processo Legislativo por código do Processo.',
            parameters: [{ name: 'id', type: 'path', description: 'ID do processo.', required: true }],
          },
          {
            id: 'getProcessoAssuntos',
            method: 'GET',
            path: '/processo/assuntos',
            description: 'Lista os Assuntos Gerais e Específicos de que tratam os Processos Legislativos.',
            parameters: [],
          },
          {
            id: 'getProcessoClasses',
            method: 'GET',
            path: '/processo/classes',
            description: 'Lista a Hierarquia de Classificações de Processos Legislativos.',
            parameters: [],
          },
          {
            id: 'getProcessoDestinos',
            method: 'GET',
            path: '/processo/destinos',
            description: 'Lista os Destinos possíveis de Processos Legislativos.',
            parameters: [],
          },
          {
            id: 'getProcessoDocumento',
            method: 'GET',
            path: '/processo/documento',
            description: 'Documentos apresentados no Processo Legislativo.',
            parameters: [],
          },
          {
            id: 'getProcessoDocumentoTipos',
            method: 'GET',
            path: '/processo/documento/tipos',
            description: 'Lista os Tipos de Documentos que podem ser apresentados em Processos Legislativos.',
            parameters: [],
          },
          {
            id: 'getProcessoDocumentoTiposConteudo',
            method: 'GET',
            path: '/processo/documento/tipos-conteudo',
            description: 'Lista os Tipos de Conteúdo Informacional que os Documentos Legislativos podem conter.',
            parameters: [],
          },
          {
            id: 'getProcessoEmenda',
            method: 'GET',
            path: '/processo/emenda',
            description: 'Lista as Emendas apresentadas em um Processo Legislativo.',
            parameters: [],
          },
          {
            id: 'getProcessoEntes',
            method: 'GET',
            path: '/processo/entes',
            description: 'Lista os Entes Jurídicos que podem participar como autores ou instâncias de tramitação.',
            parameters: [],
          },
          {
            id: 'getProcessoPrazo',
            method: 'GET',
            path: '/processo/prazo',
            description: 'Lista os Prazos Regimentais ou Constitucionais definidos no rito de tramitação.',
            parameters: [],
          },
          {
            id: 'getProcessoPrazoTipos',
            method: 'GET',
            path: '/processo/prazo/tipos',
            description: 'Tipos de Prazos de Processos Legislativos.',
            parameters: [],
          },
          {
            id: 'getProcessoRelatoria',
            method: 'GET',
            path: '/processo/relatoria',
            description: 'Relatorias de Processos Legislativos.',
            parameters: [],
          },
          {
            id: 'getProcessoSiglas',
            method: 'GET',
            path: '/processo/siglas',
            description: 'Tipos e Siglas de Documentos e Processos Legislativos.',
            parameters: [],
          },
          {
            id: 'getProcessoTiposAtualizacao',
            method: 'GET',
            path: '/processo/tipos-atualizacao',
            description: 'Tipos de Atualização que podem ocorrer em Processos Legislativos.',
            parameters: [],
          },
          {
            id: 'getProcessoTiposAutor',
            method: 'GET',
            path: '/processo/tipos-autor',
            description: 'Tipos de Autores de Documentos e Processos Legislativos.',
            parameters: [],
          },
          {
            id: 'getProcessoTiposDecisao',
            method: 'GET',
            path: '/processo/tipos-decisao',
            description: 'Tipos de Decisões que podem ocorrer em Processos Legislativos.',
            parameters: [],
          },
          {
            id: 'getProcessoTiposSituacao',
            method: 'GET',
            path: '/processo/tipos-situacao',
            description: 'Tipos de Situações (estado) possíveis em Processos Legislativos.',
            parameters: [],
          },
        ],
      },
      {
        name: 'Legislação',
        icon: LegislacaoIcon,
        description: 'Recursos relacionados à Legislação Federal.',
        endpoints: [
          {
            id: 'getLegislacaoPorCodigo',
            method: 'GET',
            path: '/legislacao/{codigo}',
            description: 'Detalhes de uma Norma Jurídica pelo código.',
            parameters: [{ name: 'codigo', type: 'path', description: 'Código da norma.', required: true }],
          },
          {
            id: 'getLegislacaoPorIdentificacao',
            method: 'GET',
            path: '/legislacao/{tipo}/{numdata}/{anoseq}',
            description: 'Detalhes de uma Norma Jurídica pela identificação (sigla/número/ano).',
            parameters: [
              { name: 'tipo', type: 'path', description: 'Tipo da norma.', required: true },
              { name: 'numdata', type: 'path', description: 'Número da norma.', required: true },
              { name: 'anoseq', type: 'path', description: 'Ano da norma.', required: true },
            ],
          },
          {
            id: 'getLegislacaoClasses',
            method: 'GET',
            path: '/legislacao/classes',
            description: 'Lista Classificação de Normas Jurídicas, Projetos e Pronunciamentos.',
            parameters: [],
          },
          {
            id: 'getLegislacaoLista',
            method: 'GET',
            path: '/legislacao/lista',
            description: 'Pesquisa de Normas Federais.',
            parameters: [],
          },
          {
            id: 'getLegislacaoTermos',
            method: 'GET',
            path: '/legislacao/termos',
            description: 'Pesquisa de Termos do Catálogo.',
            parameters: [],
          },
          {
            id: 'getLegislacaoTiposDeclaracaoDetalhe',
            method: 'GET',
            path: '/legislacao/tiposdeclaracao/detalhe',
            description: 'Lista de Detalhes de Declaração.',
            parameters: [],
          },
          {
            id: 'getLegislacaoTiposNorma',
            method: 'GET',
            path: '/legislacao/tiposNorma',
            description: 'Lista Tipos de Norma.',
            parameters: [],
          },
          {
            id: 'getLegislacaoTiposPublicacao',
            method: 'GET',
            path: '/legislacao/tiposPublicacao',
            description: 'Lista de Tipos de Publicação.',
            parameters: [],
          },
          {
            id: 'getLegislacaoTiposVide',
            method: 'GET',
            path: '/legislacao/tiposVide',
            description: 'Lista de Tipos de Vide.',
            parameters: [],
          },
          {
            id: 'getLegislacaoPorURN',
            method: 'GET',
            path: '/legislacao/urn',
            description: 'Detalhes de uma Norma Jurídica pela URN.',
            parameters: [],
          },
        ],
      },
      {
        name: 'Orçamento',
        icon: OrcamentoIcon,
        description: 'Recursos relacionados ao Orçamento.',
        endpoints: [
          {
            id: 'getOrcamentoLista',
            method: 'GET',
            path: '/orcamento/lista',
            description: 'Lotes de Emendas ao Orçamento.',
            parameters: [],
          },
          {
            id: 'getOrcamentoOficios',
            method: 'GET',
            path: '/orcamento/oficios',
            description: 'Lista os Ofícios de apoio às Emendas de Orçamento.',
            parameters: [],
          },
          {
            id: 'getOrcamentoOficiosPorNumero',
            method: 'GET',
            path: '/orcamento/oficios/{numeroSedol}',
            description: 'Recupera informações de determinado Ofício de apoio às Emendas de Orçamento.',
            parameters: [{ name: 'numeroSedol', type: 'path', description: 'Número do Sedol.', required: true }],
          },
        ],
      },
    ]
  }
];